dataset: "tiny_imagenet"
data_path: "./data/tiny-imagenet-200"
num_class: 200
model: clip
backbone: "ViT-B/16"
resolution: 224

seed: 0
gpuid: 0
num_workers: 8

epochs: 10
warmup: 1
batch_size: 64
lr: 0.03
weight_decay: 5e-4
momentum: 0.9
lnl_methods: "CE"

vpt_deep: True
vpt_len: 20

N_CTX: 16
CLASS_TOKEN_POSITION: "end"

noise_mode: 'sym'
noise_ratio: 0.0

class_names: [
 'goldfish',
 'European fire salamander',
 'bullfrog',
 'tailed frog',
 'American alligator',
 'boa constrictor',
 'trilobite',
 'scorpion',
 'black widow',
 'tarantula',
 'centipede',
 'goose',
 'koala',
 'jellyfish',
 'brain coral',
 'snail',
 'slug',
 'sea slug',
 'American lobster',
 'spiny lobster',
 'black stork',
 'king penguin',
 'albatross',
 'dugong',
 'Chihuahua',
 'Yorkshire terrier',
 'golden retriever',
 'Labrador retriever',
 'German shepherd',
 'standard poodle',
 'tabby',
 'Persian cat',
 'Egyptian cat',
 'cougar',
 'lion',
 'brown bear',
 'ladybug',
 'fly',
 'bee',
 'grasshopper',
 'walking stick',
 'cockroach',
 'mantis',
 'dragonfly',
 'monarch',
 'sulphur butterfly',
 'sea cucumber',
 'guinea pig',
 'hog',
 'ox',
 'bison',
 'bighorn',
 'gazelle',
 'Arabian camel',
 'orangutan',
 'chimpanzee',
 'baboon',
 'African elephant',
 'lesser panda',
 'abacus',
 'academic gown',
 'altar',
 'apron',
 'backpack',
 'bannister',
 'barbershop',
 'barn',
 'barrel',
 'basketball',
 'bathtub',
 'beach wagon',
 'beacon',
 'beaker',
 'beer bottle',
 'bikini',
 'binoculars',
 'birdhouse',
 'bow tie',
 'brass',
 'broom',
 'bucket',
 'bullet train',
 'butcher shop',
 'candle',
 'cannon',
 'cardigan',
 'cash machine',
 'CD player',
 'chain',
 'chest',
 'Christmas stocking',
 'cliff dwelling',
 'computer keyboard',
 'confectionery',
 'convertible',
 'crane',
 'dam',
 'desk',
 'dining table',
 'drumstick',
 'dumbbell',
 'flagpole',
 'fountain',
 'freight car',
 'frying pan',
 'fur coat',
 'gasmask',
 'go-kart',
 'gondola',
 'hourglass',
 'iPod',
 'jinrikisha',
 'kimono',
 'lampshade',
 'lawn mower',
 'lifeboat',
 'limousine',
 'magnetic compass',
 'maypole',
 'military uniform',
 'miniskirt',
 'moving van',
 'nail',
 'neck brace',
 'obelisk',
 'oboe',
 'organ',
 'parking meter',
 'pay-phone',
 'picket fence',
 'pill bottle',
 'plunger',
 'pole',
 'police van',
 'poncho',
 'pop bottle',
 "potter's wheel",
 'projectile',
 'punching bag',
 'reel',
 'refrigerator',
 'remote control',
 'rocking chair',
 'rugby ball',
 'sandal',
 'school bus',
 'scoreboard',
 'sewing machine',
 'snorkel',
 'sock',
 'sombrero',
 'space heater',
 'spider web',
 'sports car',
 'steel arch bridge',
 'stopwatch',
 'sunglasses',
 'suspension bridge',
 'swimming trunks',
 'syringe',
 'teapot',
 'teddy',
 'thatch',
 'torch',
 'tractor',
 'triumphal arch',
 'trolleybus',
 'turnstile',
 'umbrella',
 'vestment',
 'viaduct',
 'volleyball',
 'water jug',
 'water tower',
 'wok',
 'wooden spoon',
 'comic book',
 'plate',
 'guacamole',
 'ice cream',
 'ice lolly',
 'pretzel',
 'mashed potato',
 'cauliflower',
 'bell pepper',
 'mushroom',
 'orange',
 'lemon',
 'banana',
 'pomegranate',
 'meat loaf',
 'pizza',
 'potpie',
 'espresso',
 'alp',
 'cliff',
 'coral reef',
 'lakeside',
 'seashore',
 'acorn'
]